# -*- coding: utf-8 -*-
"""ensemble_stacking_gemma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVOki8JBuUF7wNeCSz1dcuyZs-SkIANd
"""

from __future__ import annotations

import json
import pickle
import random
import re
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import networkx as nx

import nltk

from scipy.sparse import csr_matrix, hstack

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import VotingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, accuracy_score


SEED = 40
random.seed(SEED)
np.random.seed(SEED)

DATA_DIR = Path("corpus")
OUT_DIR = Path("outputs")
STACK_OUT_DIR = Path("outputs_stacking_gemma")
STACK_OUT_DIR.mkdir(parents=True, exist_ok=True)

try:
    stop_words = nltk.corpus.stopwords.words("portuguese")
except LookupError:
    nltk.download("stopwords", quiet=True)
    stop_words = nltk.corpus.stopwords.words("portuguese")

def load_jsonl_df(path: Path) -> pd.DataFrame:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as e:
                raise ValueError(f"JSON inválido em {path} na linha {i}: {e}") from e
    if not rows:
        raise ValueError(f"Arquivo vazio: {path}")
    return pd.DataFrame(rows)

def create_x_y(df: pd.DataFrame) -> Tuple[pd.Series, pd.Series]:
    if "text" not in df.columns or "label" not in df.columns:
        raise ValueError(f"Esperado 'text' e 'label'. Encontrei: {list(df.columns)}")
    x = df["text"].astype(str)
    y = df["label"].astype(int).values
    return x, y

df_train = load_jsonl_df(DATA_DIR / "train.jsonl")
df_test  = load_jsonl_df(DATA_DIR / "test.jsonl")

x_train, y_train = create_x_y(df_train)
x_test, y_test   = create_x_y(df_test)

def load_graph_pkl(path: Path) -> nx.Graph:
    with path.open("rb") as f:
        obj = pickle.load(f)
    if not isinstance(obj, nx.Graph):
        raise TypeError(f"{path.name} não é nx.Graph (tipo={type(obj)})")
    return obj

G_cooc = load_graph_pkl(OUT_DIR / "KG_cooc.gpickle")
G_ppmi = load_graph_pkl(OUT_DIR / "KG_ppmi.gpickle")
G_pun  = load_graph_pkl(OUT_DIR / "KG_puncontext.gpickle")

graphs: Dict[str, nx.Graph] = {
    "cooc": G_cooc,
    "ppmi": G_ppmi,
    "pun": G_pun,
}

from scipy.sparse import diags, identity

GRAPH_EMB_DIM = 128
GRAPH_EXTRA = 2
GRAPH_FEATURE_DIM = GRAPH_EMB_DIM + GRAPH_EXTRA

TOKEN_RE = re.compile(r"[A-Za-zÀ-ÖØ-öø-ÿ]+", re.UNICODE)

def tokenize_for_graph(text: str) -> List[str]:
    return [t.lower() for t in TOKEN_RE.findall(text)]

def nx_to_sparse_adjacency(G: nx.Graph, nodelist: List[str], weight: str = "weight") -> csr_matrix:
    if hasattr(nx, "to_scipy_sparse_array"):
        A = nx.to_scipy_sparse_array(G, nodelist=nodelist, weight=weight, dtype=float, format="csr")
        return csr_matrix(A)
    return nx.to_scipy_sparse_matrix(G, nodelist=nodelist, weight=weight, dtype=float, format="csr")

def normalize_adjacency(A: csr_matrix, add_self_loops: bool = True) -> csr_matrix:
    A = A.tocsr(copy=True)
    if add_self_loops:
        A = A + identity(A.shape[0], format="csr", dtype=A.dtype)

    deg = np.array(A.sum(axis=1)).ravel()
    deg[deg == 0] = 1.0
    inv_sqrt = 1.0 / np.sqrt(deg)

    D_inv_sqrt = diags(inv_sqrt, format="csr")
    return (D_inv_sqrt @ A @ D_inv_sqrt).tocsr()

def build_node_embeddings_svd(G: nx.Graph, dim: int, seed: int) -> Tuple[Dict[str, int], np.ndarray]:
    nodelist = list(G.nodes())
    node_to_idx = {n: i for i, n in enumerate(nodelist)}
    A = nx_to_sparse_adjacency(G, nodelist=nodelist, weight="weight")

    if A.nnz > 0:
        A = A.tocsr(copy=True)
        A.data = np.log1p(A.data)

    A_norm = normalize_adjacency(A, add_self_loops=True)

    svd = TruncatedSVD(n_components=dim, random_state=seed)
    node_emb = svd.fit_transform(A_norm).astype(np.float32)
    return node_to_idx, node_emb


def doc_features_from_graph(texts: List[str], node_to_idx: Dict[str, int], node_emb: np.ndarray) -> np.ndarray:
    n = len(texts)
    feats = np.zeros((n, GRAPH_FEATURE_DIM), dtype=np.float32)
    for i, txt in enumerate(texts):
        toks = tokenize_for_graph(txt)
        if not toks:
            continue
        idxs = [node_to_idx[t] for t in toks if t in node_to_idx]
        hits = len(idxs)
        total = len(toks)
        if hits > 0:
            feats[i, :GRAPH_EMB_DIM] = node_emb[idxs].mean(axis=0)
        feats[i, GRAPH_EMB_DIM] = (hits / total) if total > 0 else 0.0
        feats[i, GRAPH_EMB_DIM + 1] = np.log1p(hits)
    return feats

node_models: Dict[str, Dict[str, object]] = {}
for k, G in graphs.items():
    node_to_idx, node_emb = build_node_embeddings_svd(G, dim=GRAPH_EMB_DIM, seed=SEED)
    node_models[k] = {"node_to_idx": node_to_idx, "node_emb": node_emb}

graph_feats: Dict[str, Dict[str, np.ndarray]] = {k: {} for k in graphs.keys()}
for k in graphs.keys():
    node_to_idx = node_models[k]["node_to_idx"]
    node_emb = node_models[k]["node_emb"]
    graph_feats[k]["train"] = doc_features_from_graph(x_train.tolist(), node_to_idx, node_emb)
    graph_feats[k]["test"]  = doc_features_from_graph(x_test.tolist(),  node_to_idx, node_emb)

def stack_graph_blocks(keys: List[str], split: str) -> np.ndarray:
    blocks = [graph_feats[k][split] for k in keys]
    return np.hstack(blocks).astype(np.float32)

def eval_model(name, model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"{name} ACC:", acc)
    print(classification_report(y_test, y_pred))
    return acc

def make_vectorizer() -> TfidfVectorizer:
    return TfidfVectorizer(ngram_range=(1, 2), stop_words=stop_words)

def make_baseline_voter() -> VotingClassifier:
    rf_model = RandomForestClassifier(n_estimators=100, criterion="entropy", max_depth=15, random_state=SEED)
    lr_model = LogisticRegression(random_state=SEED, max_iter=2000)
    svm_model = SVC(probability=True, random_state=SEED)
    return VotingClassifier(
        estimators=[("rf", rf_model), ("lr", lr_model), ("svm", svm_model)],
        voting="soft",
        n_jobs=1,
    )

def build_fused_mats(vec: TfidfVectorizer, Xtr_text, Xsp_text, Xtr_g_raw: np.ndarray, Xsp_g_raw: np.ndarray):
    scaler = StandardScaler()
    scaler.fit(Xtr_g_raw)
    Xtr_g = scaler.transform(Xtr_g_raw).astype(np.float32)
    Xsp_g = scaler.transform(Xsp_g_raw).astype(np.float32)

    Xtr = hstack([Xtr_text, csr_matrix(Xtr_g)], format="csr")
    Xsp = hstack([Xsp_text, csr_matrix(Xsp_g)], format="csr")

    Xtr = ensure_csr_writeable(Xtr)
    Xsp = ensure_csr_writeable(Xsp)

    return Xtr, Xsp

def build_fused_mats_dense(Xtr_text_dense: np.ndarray, Xsp_text_dense: np.ndarray,
                          Xtr_g_raw: np.ndarray, Xsp_g_raw: np.ndarray):
    scaler = StandardScaler()
    scaler.fit(Xtr_g_raw)
    Xtr_g = scaler.transform(Xtr_g_raw).astype(np.float32)
    Xsp_g = scaler.transform(Xsp_g_raw).astype(np.float32)

    Xtr = np.hstack([Xtr_text_dense, Xtr_g]).astype(np.float32)
    Xsp = np.hstack([Xsp_text_dense, Xsp_g]).astype(np.float32)
    return Xtr, Xsp

import os
import hashlib
from pathlib import Path
from typing import Optional
import numpy as np

from sentence_transformers import SentenceTransformer
import torch

EMB_MODEL_NAME = "google/embeddinggemma-300m"
EMB_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

CACHE_DIR = Path("cache_embeddings")
CACHE_DIR.mkdir(parents=True, exist_ok=True)

def fingerprint_texts(texts):
    h = hashlib.sha1()
    for t in texts:
        t = t if isinstance(t, str) else str(t)
        b = t.encode("utf-8", errors="ignore")
        h.update(len(b).to_bytes(8, "little"))
        h.update(b)
    return h.hexdigest()

def cache_path(split_name, texts, model_name):
    safe = re.sub(r"[^a-zA-Z0-9._-]+", "_", model_name)
    fp = fingerprint_texts(texts)
    return CACHE_DIR / f"emb_{safe}_{split_name}_{fp}.npz"

_embedder: Optional[SentenceTransformer] = None

def get_embedder():
    global _embedder
    if _embedder is None:
        _embedder = SentenceTransformer(
            EMB_MODEL_NAME,
            device=EMB_DEVICE,
            trust_remote_code=True,
        )
    return _embedder

def compute_embeddings(texts, batch_size=32, normalize=True):
    model = get_embedder()
    emb = model.encode(
        texts,
        batch_size=batch_size,
        show_progress_bar=True,
        normalize_embeddings=normalize,
    )
    return np.asarray(emb, dtype=np.float32)

def load_or_compute_embeddings(split_name, texts, batch_size=32):
    p = cache_path(split_name, texts, EMB_MODEL_NAME)
    if p.exists():
        return np.load(p)["emb"].astype(np.float32)
    emb = compute_embeddings(texts, batch_size=batch_size, normalize=True)
    np.savez_compressed(p, emb=emb.astype(np.float16))
    return emb

x_train_list = x_train.tolist()
x_test_list  = x_test.tolist()

E_train = load_or_compute_embeddings("train", x_train_list, batch_size=32)
E_test  = load_or_compute_embeddings("test",  x_test_list,  batch_size=32)

print("Embeddings:", E_train.shape, E_test.shape, "| device:", EMB_DEVICE)

from scipy.sparse import isspmatrix_csr

def ensure_csr_writeable(X):
    X = X.tocsr(copy=True)
    X.sort_indices()
    if hasattr(X.data, "flags") and not X.data.flags.writeable:
        X.data = np.array(X.data, copy=True)
    if hasattr(X.indices, "flags") and not X.indices.flags.writeable:
        X.indices = np.array(X.indices, copy=True)
    if hasattr(X.indptr, "flags") and not X.indptr.flags.writeable:
        X.indptr = np.array(X.indptr, copy=True)
    return X

def proba_to_meta_features(proba: np.ndarray) -> np.ndarray:
    p = np.clip(proba.astype(np.float32), 1e-7, 1.0 - 1e-7)
    maxp = np.max(p, axis=1, keepdims=True)
    ent = -(p * np.log(p)).sum(axis=1, keepdims=True)
    return np.hstack([p, maxp, ent]).astype(np.float32)

candidate_specs = [
    ("text_tfidf", []),
    ("text_emb",   []),

    ("cooc_tfidf", ["cooc"]),
    ("ppmi_tfidf", ["ppmi"]),
    ("pun_tfidf",  ["pun"]),
    ("all_tfidf",  ["cooc", "ppmi", "pun"]),

    ("cooc_emb",   ["cooc"]),
    ("ppmi_emb",   ["ppmi"]),
    ("pun_emb",    ["pun"]),
    ("all_emb",    ["cooc", "ppmi", "pun"]),
]

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

oof_full = np.zeros((len(x_train), 4 * len(candidate_specs)), dtype=np.float32)

x_train_list = x_train.tolist()

for fold_id, (tr_idx, va_idx) in enumerate(skf.split(np.zeros(len(y_train)), y_train), start=1):
    x_tr = [x_train_list[i] for i in tr_idx]
    x_va = [x_train_list[i] for i in va_idx]
    y_tr = y_train[tr_idx]

    vec = make_vectorizer()
    Xtr_tfidf = vec.fit_transform(x_tr)
    Xva_tfidf = vec.transform(x_va)

    Xtr_emb = E_train[tr_idx]
    Xva_emb = E_train[va_idx]

    for m_i, (name, gkeys) in enumerate(candidate_specs):
        model = make_baseline_voter()

        is_tfidf = name.endswith("_tfidf")
        is_emb   = name.endswith("_emb")

        if name.startswith("text_"):
            if is_tfidf:
                model.fit(Xtr_tfidf, y_tr)
                proba = model.predict_proba(Xva_tfidf)
            else:
                model.fit(Xtr_emb, y_tr)
                proba = model.predict_proba(Xva_emb)

        else:
            Xtr_g_raw = stack_graph_blocks(gkeys, "train")[tr_idx]
            Xva_g_raw = stack_graph_blocks(gkeys, "train")[va_idx]

            if is_tfidf:
                Xtr_fused, Xva_fused = build_fused_mats(vec, Xtr_tfidf, Xva_tfidf, Xtr_g_raw, Xva_g_raw)
                model.fit(Xtr_fused, y_tr)
                proba = model.predict_proba(Xva_fused)
            else:
                Xtr_fused, Xva_fused = build_fused_mats_dense(Xtr_emb, Xva_emb, Xtr_g_raw, Xva_g_raw)
                model.fit(Xtr_fused, y_tr)
                proba = model.predict_proba(Xva_fused)

        feats = proba_to_meta_features(proba)
        oof_full[va_idx, (4*m_i):(4*m_i+4)] = feats

def oof_acc_for_spec(oof_mat: np.ndarray, spec_index: int) -> float:
    p = oof_mat[:, (4*spec_index):(4*spec_index+2)]
    y_pred = np.argmax(p, axis=1)
    return float((y_pred == y_train).mean())

accs = [(name, oof_acc_for_spec(oof_full, i)) for i, (name, _) in enumerate(candidate_specs)]
accs_sorted = sorted(accs, key=lambda t: t[1], reverse=True)

selected_specs_all  = candidate_specs[:]

sel_idx_all  = list(range(len(candidate_specs)))

oof_all  = np.hstack([oof_full[:, (4*i):(4*i+4)] for i in sel_idx_all]).astype(np.float32)

print("OOF accs:", accs_sorted)
print("Specs ALL :", [n for n, _ in selected_specs_all])
print("oof_all  shape:", oof_all.shape)

meta_cooc = RandomForestClassifier(n_estimators=100, criterion="entropy", max_depth=15, random_state=SEED)
meta_ppmi = RandomForestClassifier(n_estimators=100, criterion="entropy", max_depth=15, random_state=SEED)
meta_pun  = RandomForestClassifier(n_estimators=100, criterion="entropy", max_depth=15, random_state=SEED)
meta_all  = RandomForestClassifier(n_estimators=100, criterion="entropy", max_depth=15, random_state=SEED)

idx = {n: i for i, (n, _) in enumerate(candidate_specs)}

idx = {n: i for i, (n, _) in enumerate(candidate_specs)}

def oof_pair(a: str, b: str) -> np.ndarray:
    return np.hstack([
        oof_full[:, (4*idx[a]):(4*idx[a]+4)],
        oof_full[:, (4*idx[b]):(4*idx[b]+4)],
    ]).astype(np.float32)

oof_text_cooc_tfidf = oof_pair("text_tfidf", "cooc_tfidf")
oof_text_ppmi_tfidf = oof_pair("text_tfidf", "ppmi_tfidf")
oof_text_pun_tfidf  = oof_pair("text_tfidf", "pun_tfidf")

oof_text_cooc_emb = oof_pair("text_emb", "cooc_emb")
oof_text_ppmi_emb = oof_pair("text_emb", "ppmi_emb")
oof_text_pun_emb  = oof_pair("text_emb", "pun_emb")

meta_cooc.fit(oof_text_cooc_tfidf, y_train)
meta_ppmi.fit(oof_text_ppmi_tfidf, y_train)
meta_pun.fit(oof_text_pun_tfidf,  y_train)

meta_all.fit(oof_all, y_train)

vec_full = make_vectorizer()
Xtr_tfidf_full = ensure_csr_writeable(vec_full.fit_transform(x_train.tolist()))
Xte_tfidf_full = ensure_csr_writeable(vec_full.transform(x_test.tolist()))

assert Xtr_tfidf_full.shape[0] == len(y_train), "Xtr_tfidf_full e y_train com tamanhos diferentes"
assert Xte_tfidf_full.shape[0] == len(y_test), "Xte_tfidf_full e y_test com tamanhos diferentes"

Xtr_emb_full = E_train
Xte_emb_full = E_test

probas_test_by_name = {}

Z_test_all = np.zeros((len(x_test), 4 * len(candidate_specs)), dtype=np.float32)

for m_i, (name, gkeys) in enumerate(candidate_specs):
    model = make_baseline_voter()

    is_tfidf = name.endswith("_tfidf")
    is_emb   = name.endswith("_emb")

    if name.startswith("text_"):
        if is_tfidf:
            model.fit(Xtr_tfidf_full, y_train)
            proba_test = model.predict_proba(Xte_tfidf_full)
        else:
            model.fit(Xtr_emb_full, y_train)
            proba_test = model.predict_proba(Xte_emb_full)
    else:
        Xtr_g_raw = stack_graph_blocks(gkeys, "train")
        Xte_g_raw = stack_graph_blocks(gkeys, "test")

        if is_tfidf:
            Xtr_fused, Xte_fused = build_fused_mats(vec_full, Xtr_tfidf_full, Xte_tfidf_full, Xtr_g_raw, Xte_g_raw)
            model.fit(Xtr_fused, y_train)
            proba_test = model.predict_proba(Xte_fused)
        else:
            Xtr_fused, Xte_fused = build_fused_mats_dense(Xtr_emb_full, Xte_emb_full, Xtr_g_raw, Xte_g_raw)
            model.fit(Xtr_fused, y_train)
            proba_test = model.predict_proba(Xte_fused)

    probas_test_by_name[name] = proba_test.astype(np.float32)
    Z_test_all[:, (4*m_i):(4*m_i+4)] = proba_to_meta_features(proba_test)

idx = {n: i for i, (n, _) in enumerate(candidate_specs)}

idx = {n: i for i, (n, _) in enumerate(candidate_specs)}

def z_pair(a: str, b: str) -> np.ndarray:
    return np.hstack([
        Z_test_all[:, (4*idx[a]):(4*idx[a]+4)],
        Z_test_all[:, (4*idx[b]):(4*idx[b]+4)],
    ]).astype(np.float32)

Z_test_text_cooc_tfidf = z_pair("text_tfidf", "cooc_tfidf")
Z_test_text_ppmi_tfidf = z_pair("text_tfidf", "ppmi_tfidf")
Z_test_text_pun_tfidf  = z_pair("text_tfidf", "pun_tfidf")

Z_test_text_cooc_emb = z_pair("text_emb", "cooc_emb")
Z_test_text_ppmi_emb = z_pair("text_emb", "ppmi_emb")
Z_test_text_pun_emb  = z_pair("text_emb", "pun_emb")

def predict_from_proba(proba: np.ndarray) -> np.ndarray:
    return np.argmax(proba, axis=1)

rows = []
for name, _ in candidate_specs:
    proba = probas_test_by_name[name]
    y_pred = predict_from_proba(proba)
    acc = accuracy_score(y_test, y_pred)
    print(f"\n=== {name.upper()} (TEST) ===")
    print("acc:", acc)
    print(classification_report(y_test, y_pred))
    rows.append((name, acc))

print("\nResumo (acc):")
for name, acc in sorted(rows, key=lambda x: x[1], reverse=True):
    print(f"{name:>6} -> {acc:.4f}")

y_pred_text_tfidf = np.argmax(probas_test_by_name["text_tfidf"], axis=1)
y_pred_text_emb   = np.argmax(probas_test_by_name["text_emb"], axis=1)

y_pred_cooc_tfidf = np.argmax(probas_test_by_name["cooc_tfidf"], axis=1)
y_pred_ppmi_tfidf = np.argmax(probas_test_by_name["ppmi_tfidf"], axis=1)
y_pred_pun_tfidf  = np.argmax(probas_test_by_name["pun_tfidf"], axis=1)
y_pred_all_tfidf  = np.argmax(probas_test_by_name["all_tfidf"], axis=1)

y_pred_cooc_emb = np.argmax(probas_test_by_name["cooc_emb"], axis=1)
y_pred_ppmi_emb = np.argmax(probas_test_by_name["ppmi_emb"], axis=1)
y_pred_pun_emb  = np.argmax(probas_test_by_name["pun_emb"], axis=1)
y_pred_all_emb  = np.argmax(probas_test_by_name["all_emb"], axis=1)

y_pred_stack_cooc = meta_cooc.predict(Z_test_text_cooc_tfidf)
acc_stack_cooc = accuracy_score(y_test, y_pred_stack_cooc)
print("STACKING TEXT+COOC (A+B) TEST ACC:", acc_stack_cooc)
print(classification_report(y_test, y_pred_stack_cooc))

y_pred_stack_ppmi = meta_ppmi.predict(Z_test_text_ppmi_tfidf)
acc_stack_ppmi = accuracy_score(y_test, y_pred_stack_ppmi)
print("STACKING TEXT+PPMI (A+B) TEST ACC:", acc_stack_ppmi)
print(classification_report(y_test, y_pred_stack_ppmi))

y_pred_stack_pun  = meta_pun.predict(Z_test_text_pun_tfidf)
acc_stack_pun = accuracy_score(y_test, y_pred_stack_pun)
print("STACKING TEXT+PUN (A+B) TEST ACC:", acc_stack_pun)
print(classification_report(y_test, y_pred_stack_pun))

y_pred_stack_all = meta_all.predict(Z_test_all)
acc_stack_all = accuracy_score(y_test, y_pred_stack_all)
print("STACKING ALL (A+B) TEST ACC:", acc_stack_all)
print(classification_report(y_test, y_pred_stack_all))

y_pred_base = np.argmax(probas_test_by_name["text_tfidf"], axis=1)
acc_base = accuracy_score(y_test, y_pred_base)
print("BASELINE (TF-IDF) TEST ACC:", acc_base)
print(classification_report(y_test, y_pred_base))

PUNS_PATH = Path("corpus/puns.json")

with PUNS_PATH.open("r", encoding="utf-8") as f:
    puns_meta = json.load(f)

def classify_pun_type(signs):
    if not signs:
        return "nenhum"

    has_homograph = any(bool(s.get("homograph", False)) for s in signs)
    has_homophone = any(bool(s.get("homophone", False)) for s in signs)
    has_both = any(
        bool(s.get("homograph", False)) and bool(s.get("homophone", False))
        for s in signs
    )

    if has_both:
        return "ambos"
    if has_homograph:
        return "homografos"
    if has_homophone:
        return "homonimos"
    return "nenhum"

puns_df = pd.DataFrame(puns_meta)
puns_df["pun_type"] = puns_df["signs"].apply(classify_pun_type)
puns_df = puns_df[["text", "pun_type", "signs"]].drop_duplicates(subset=["text"])

analysis_df = df_test.copy().reset_index(drop=True)
analysis_df["y_true"] = y_test
analysis_df = analysis_df.merge(puns_df, on="text", how="left")
analysis_df["pun_type"] = analysis_df["pun_type"].fillna("nenhum")
analysis_df["signs"] = analysis_df["signs"].apply(
    lambda x: x if isinstance(x, list) else []
)

# ANALISAR CADA CONFIGURAÇÃO FINAL TREINADA
models_to_analyze = {
    "stack_cooc": y_pred_stack_cooc,
    "stack_ppmi": y_pred_stack_ppmi,
    "stack_pun": y_pred_stack_pun,
    "stack_all": y_pred_stack_all,
}

def compute_confusion_counts(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    tp = int(((y_true == 1) & (y_pred == 1)).sum())
    tn = int(((y_true == 0) & (y_pred == 0)).sum())
    fp = int(((y_true == 0) & (y_pred == 1)).sum())
    fn = int(((y_true == 1) & (y_pred == 0)).sum())

    return {"TP": tp, "TN": tn, "FP": fp, "FN": fn}

def add_confusion_cell(df):
    df = df.copy()
    df["confusion_cell"] = np.where(
        (df["y_true"] == 1) & (df["y_pred"] == 1), "TP",
        np.where(
            (df["y_true"] == 0) & (df["y_pred"] == 0), "TN",
            np.where(
                (df["y_true"] == 0) & (df["y_pred"] == 1), "FP",
                "FN"
            )
        )
    )
    return df

def summarize_pun_types(df):
    order = ["homonimos", "homografos", "ambos", "nenhum"]
    counts = df["pun_type"].value_counts()
    return {ptype: int(counts.get(ptype, 0)) for ptype in order}

for model_name, y_pred in models_to_analyze.items():
    print(f"\n{'='*60}")
    print(f"CONFIGURAÇÃO FINAL: {model_name}")
    print(f"{'='*60}")

    counts = compute_confusion_counts(analysis_df["y_true"].values, y_pred)
    print("TP, TN, FP, FN:")
    print(counts)

    tmp = analysis_df.copy()
    tmp["y_pred"] = y_pred
    tmp = add_confusion_cell(tmp)

    print("\nDistribuição por tipo de trocadilho nos FN:")
    print(summarize_pun_types(tmp[tmp["confusion_cell"] == "FN"]))

    print("\nDistribuição por tipo de trocadilho nos TP:")
    print(summarize_pun_types(tmp[tmp["confusion_cell"] == "TP"]))

    print("\nDistribuição por tipo de trocadilho nos FP:")
    print(summarize_pun_types(tmp[tmp["confusion_cell"] == "FP"]))

    print("\nDistribuição por tipo de trocadilho nos TN:")
    print(summarize_pun_types(tmp[tmp["confusion_cell"] == "TN"]))

rows = []

for model_name, y_pred in models_to_analyze.items():
    tmp = analysis_df.copy()
    tmp["y_pred"] = y_pred
    tmp = add_confusion_cell(tmp)
    tmp["model"] = model_name

    cols = ["model", "text", "label", "y_true", "y_pred", "confusion_cell", "pun_type", "signs"]
    rows.append(tmp[cols])

pun_cases_df = pd.concat(rows, ignore_index=True)
pun_cases_df.to_csv(STACK_OUT_DIR / "pun_cases.csv", index=False)

print(f"\nArquivo único salvo em: {STACK_OUT_DIR / 'pun_cases.csv'}")